version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql

  backend:
    build:
      context: ./Backend/SilkyRoad.API
    ports:
      - "7001:7001"
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=db;Database=SilkyRoadDb;User=sa;Password=Your_password123;TrustServerCertificate=True;
    depends_on:
      - db
    volumes:
      - ./Backend/SilkyRoad.API/wwwroot/uploads:/app/wwwroot/uploads

  frontend:
    build:
      context: ./Frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mssqldata: 